# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "12203900bc4650c64307c4a1b47d1fc1"
application_url = "https://example.com"
embedded = true
name = "Ai-App"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,read_orders,read_products,write_draft_orders,write_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
